<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Schedule a Demo</name>
   <tag></tag>
   <elementGuidId>78b322da-9a17-4659-9af9-f66e9a1f64c4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-item-1637']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#menu-item-1637 > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>736602ea-be99-48fc-9e74-1d7529bdcc16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://redapple.ai/contact-us/#demo</value>
      <webElementGuid>a0a46fca-0936-4a53-b187-efc2b94a9eeb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Schedule a Demo</value>
      <webElementGuid>ade3426f-15e7-464d-a4e8-ce55d7a3825c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;site-header&quot;)/div[@class=&quot;header-inner&quot;]/nav[@class=&quot;site-navigation show&quot;]/div[@class=&quot;menu-main-menu-container&quot;]/ul[@id=&quot;menu-main-menu&quot;]/li[@id=&quot;menu-item-1637&quot;]/a[1]</value>
      <webElementGuid>7fbde0b4-dd51-499f-89ec-55096a3469ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1593c776-483a-439d-a710-231961aa51f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://redapple.ai/contact-us/#demo</value>
      <webElementGuid>6e05de5f-4cbd-4835-9eba-d2fb1031901e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Schedule a Demo</value>
      <webElementGuid>234e5693-db78-4b73-8655-da37c15526da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;site-header&quot;)/div[@class=&quot;header-inner&quot;]/nav[@class=&quot;site-navigation show&quot;]/div[@class=&quot;menu-main-menu-container&quot;]/ul[@id=&quot;menu-main-menu&quot;]/li[@id=&quot;menu-item-1637&quot;]/a[1]</value>
      <webElementGuid>fe94f1cc-7391-445e-b345-d9a135033acd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menu-item-1637']/a</value>
      <webElementGuid>c9c61c68-af84-4bec-b809-43be15c14661</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Schedule a Demo')]</value>
      <webElementGuid>108f1d7a-7782-45bd-b3a9-de3e86b5deb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact'])[1]/following::a[1]</value>
      <webElementGuid>6f2e8d44-c4ec-4630-b3af-861cb50a8575</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Blog'])[1]/following::a[2]</value>
      <webElementGuid>da44c309-7bcd-4a39-99e0-91be99280115</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login'])[1]/preceding::a[1]</value>
      <webElementGuid>db23f979-5dfc-4453-b27d-38094036a827</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Menu'])[1]/preceding::a[2]</value>
      <webElementGuid>6960a0cc-9131-4a08-8567-ed7aca43dc57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Schedule a Demo']/parent::*</value>
      <webElementGuid>e082b3b7-808f-4b0d-98bc-14586e7ae0d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://redapple.ai/contact-us/#demo')]</value>
      <webElementGuid>64817332-4402-4be7-8b46-fd0d5a2793f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/a</value>
      <webElementGuid>19307fb5-fe19-4dce-bc1a-cee0b6aeb9bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://redapple.ai/contact-us/#demo' and (text() = 'Schedule a Demo' or . = 'Schedule a Demo')]</value>
      <webElementGuid>116c50db-0dac-4cf2-8f31-5da12f703374</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
