<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Home_custom-logo</name>
   <tag></tag>
   <elementGuidId>2fffa464-a187-4c4c-af5d-02bd7ac5e5f7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//header[@id='site-header']/div/div/div/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.custom-logo</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>61bda3ba-b657-4c6d-8b74-a9414fff9391</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>667</value>
      <webElementGuid>3400e49d-d2da-422f-b0d3-c93398d37226</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>163</value>
      <webElementGuid>c97139fe-f84d-4c83-baac-5c9f20339757</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://redappleapp.com/wp-content/uploads/2022/08/RedappleLogo.png</value>
      <webElementGuid>001f8f69-0228-444e-94bf-0c1a99ff02d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom-logo</value>
      <webElementGuid>3f00d970-5b7d-4221-b271-a5738fdc96cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Redapple Digital Health, Inc.</value>
      <webElementGuid>541e32da-3163-44f2-82f5-5c76af0d062c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>https://redappleapp.com/wp-content/uploads/2022/08/RedappleLogo.png 667w, https://redappleapp.com/wp-content/uploads/2022/08/RedappleLogo-300x73.png 300w</value>
      <webElementGuid>ed19abfb-e76b-4b2e-82b7-e993c380e996</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sizes</name>
      <type>Main</type>
      <value>(max-width: 667px) 100vw, 667px</value>
      <webElementGuid>09c5f6d4-9ef3-4846-be24-ec5d41dd91e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;site-header&quot;)/div[@class=&quot;header-inner&quot;]/div[@class=&quot;site-branding show-logo&quot;]/div[@class=&quot;site-logo show&quot;]/a[@class=&quot;custom-logo-link&quot;]/img[@class=&quot;custom-logo&quot;]</value>
      <webElementGuid>44df09ab-f7a0-4034-9b0e-ee48aba02a89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>1285a6dc-6afb-4835-aaa5-f7bcdf8258c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>667</value>
      <webElementGuid>b728bdb0-cf90-4e67-b29f-a762bd2458b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>163</value>
      <webElementGuid>2aa1875a-e708-461e-ada9-235aa02aa289</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://redappleapp.com/wp-content/uploads/2022/08/RedappleLogo.png</value>
      <webElementGuid>cccb5b86-ec05-4a20-8b65-ce6f2710104f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom-logo</value>
      <webElementGuid>918b153e-c47d-482d-8856-a08547445a5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Redapple Digital Health, Inc.</value>
      <webElementGuid>c3e8faec-4751-4e33-a425-17871c75714f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>https://redappleapp.com/wp-content/uploads/2022/08/RedappleLogo.png 667w, https://redappleapp.com/wp-content/uploads/2022/08/RedappleLogo-300x73.png 300w</value>
      <webElementGuid>7a4b6d7c-ac7f-4462-8654-3123f406abf5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sizes</name>
      <type>Main</type>
      <value>(max-width: 667px) 100vw, 667px</value>
      <webElementGuid>473d6f68-8965-4e12-816e-2515603b2e69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;site-header&quot;)/div[@class=&quot;header-inner&quot;]/div[@class=&quot;site-branding show-logo&quot;]/div[@class=&quot;site-logo show&quot;]/a[@class=&quot;custom-logo-link&quot;]/img[@class=&quot;custom-logo&quot;]</value>
      <webElementGuid>34f7cec6-ab61-4321-abe7-7b7e70866400</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='site-header']/div/div/div/a/img</value>
      <webElementGuid>67e31f11-3176-447b-a776-4fecdc688b4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Redapple Digital Health, Inc.']</value>
      <webElementGuid>df3e3e3c-9837-485e-9bc9-a130b82936ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>ddd2b37e-ee76-4ecd-b286-a5516b406b9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://redappleapp.com/wp-content/uploads/2022/08/RedappleLogo.png' and @alt = 'Redapple Digital Health, Inc.']</value>
      <webElementGuid>66b6a14b-30df-4246-9bf7-41391e85c29f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
