<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Home_nocss</name>
   <tag></tag>
   <elementGuidId>a6bcc8ca-2b33-408f-9610-d811eaa131c9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//header[@id='site-header']/div/div/div/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.nocss</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>dd32d8a1-8691-43b1-812a-920124cf561d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nocss</value>
      <webElementGuid>59dc096e-fdca-4206-aeb6-4552bc40bb7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://redappleapp.com/wp-content/uploads/2022/10/redapple-logo-white-v2.png</value>
      <webElementGuid>c0b1bf47-bf5f-4e97-8159-056712ef4e09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;site-header&quot;)/div[@class=&quot;header-inner&quot;]/div[@class=&quot;site-branding show-logo&quot;]/div[@class=&quot;site-logo show&quot;]/a[@class=&quot;custom-logo-link&quot;]/img[@class=&quot;nocss&quot;]</value>
      <webElementGuid>2748707d-9401-4e19-a619-ad233e34583f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='site-header']/div/div/div/a/img</value>
      <webElementGuid>c296e3b3-e39f-463b-abf4-3fbd8513af4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://redappleapp.com/wp-content/uploads/2022/10/redapple-logo-white-v2.png')]</value>
      <webElementGuid>f7ec1153-2fe8-47fc-a0a0-a88aa145d8f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>abf6bdf7-de03-4ea7-aead-c14c20b25517</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://redappleapp.com/wp-content/uploads/2022/10/redapple-logo-white-v2.png']</value>
      <webElementGuid>f6bf9374-a01f-4f6f-8c94-4085ba309c3d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
