<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Signup</name>
   <tag></tag>
   <elementGuidId>ad378438-c93a-4bbf-9300-b7a56e830012</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[2]/div/div/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.sc-eEOqmf.dKMLgX</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>fb8f59f7-9454-44af-be8d-8109a6c52cff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-eEOqmf dKMLgX</value>
      <webElementGuid>8902aedc-6fd2-4afd-b717-28c310bbb992</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Signup</value>
      <webElementGuid>0a83426b-3b62-45a7-9c6b-a11806c73f96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;sc-jdzWJC bLA-DlK&quot;]/div[@class=&quot;sc-fCdBJp gBtVNX&quot;]/div[@class=&quot;sc-ESujJ hECkyJ&quot;]/div[@class=&quot;sc-jWEIYm jBzXOH&quot;]/div[@class=&quot;sc-eEOqmf dKMLgX&quot;]</value>
      <webElementGuid>d6edb63c-ecdd-45f1-b0af-8481ffca10b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d65d6ee2-2dde-4cb9-9886-6318f80c0a16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-eEOqmf dKMLgX</value>
      <webElementGuid>1fe17c02-a646-44d0-8d46-18c93fd7794d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Signup</value>
      <webElementGuid>521e9e20-2c62-4621-b579-f9ad7890627d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;sc-jdzWJC bLA-DlK&quot;]/div[@class=&quot;sc-fCdBJp gBtVNX&quot;]/div[@class=&quot;sc-ESujJ hECkyJ&quot;]/div[@class=&quot;sc-jWEIYm jBzXOH&quot;]/div[@class=&quot;sc-eEOqmf dKMLgX&quot;]</value>
      <webElementGuid>7a64bd8f-b31b-4dcb-ac14-2fd290590aa4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div/div/div[2]</value>
      <webElementGuid>550717d7-3663-4ade-b882-dc37f2c77826</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login'])[1]/following::div[1]</value>
      <webElementGuid>c4b7d154-4aba-4c53-9f51-6f7ec2b1fe7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='LOGIN'])[1]/following::div[7]</value>
      <webElementGuid>9db36b0a-7334-432e-852b-6306dcffaac9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='If you are already registered'])[1]/preceding::div[2]</value>
      <webElementGuid>b6e4a55a-5a34-4a35-b11d-2f44e644bac2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log in'])[1]/preceding::div[5]</value>
      <webElementGuid>781399ca-ed93-467b-a8a0-b0302f45584b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Signup']/parent::*</value>
      <webElementGuid>0e9114bd-184d-4a3c-a03e-b57fc8a1790c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]</value>
      <webElementGuid>1f2bec52-7491-48a3-8a44-c9a479ab2db6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Signup' or . = 'Signup')]</value>
      <webElementGuid>b324281e-83d6-436e-a2b8-c532ce207ce7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
