<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_redappledigitalhealth</name>
   <tag></tag>
   <elementGuidId>0bc6d338-9794-441f-96c4-efa077809b42</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mount_0_0_YN']/div/div/div/div/div/div/div/div/section/main/div/header/section/div/h2</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h2._aacl._aacs._aact._aacx._aada</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>d470b4fc-800c-4ae3-bfe3-7fb211597df2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_aacl _aacs _aact _aacx _aada</value>
      <webElementGuid>5ace660e-070b-4614-a7de-96aabed3334f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>redappledigitalhealth</value>
      <webElementGuid>83db56c5-3c26-47b6-8569-0ef1f4f408ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mount_0_0_YN&quot;)/div[1]/div[1]/div[@class=&quot;x9f619 x1n2onr6 x1ja2u2z&quot;]/div[@class=&quot;x9f619 x1n2onr6 x1ja2u2z&quot;]/div[@class=&quot;x78zum5 xdt5ytf x1n2onr6 x1ja2u2z&quot;]/div[@class=&quot;x78zum5 xdt5ytf x1n2onr6&quot;]/div[@class=&quot;x78zum5 xdt5ytf x1n2onr6 xat3117 xxzkxad&quot;]/div[@class=&quot;x78zum5 xdt5ytf x10cihs4 x1t2pt76 x1n2onr6 x1ja2u2z&quot;]/section[@class=&quot;_a997 _a998&quot;]/main[@class=&quot;_a993 _a995&quot;]/div[@class=&quot;_aa_y _aa_z&quot;]/header[@class=&quot;x1qjc9v5 x78zum5 x1q0g3np x2lah0s x1n2onr6 xc2v4qs x1qsaojo x1xl8k2i x1kcpa7z x1ez9qw7&quot;]/section[@class=&quot;x1qjc9v5 x6umtig x1b1mbwd xaqea5y xav7gou x9f619 x5n08af x78zum5 xdt5ytf xs83m0k xeuugli xdj266r x11i5rnm xat24cr x1mh8g0r xexx8yu x4uap5 x18d9i69 xkhd6sd x1n2onr6 xk390pu x11njtxf x139hhg0 x1qgnrqa xg1prrt x1quol0o&quot;]/div[@class=&quot;x6s0dn4 x78zum5 x1q0g3np xs83m0k xeuugli x1n2onr6&quot;]/h2[@class=&quot;_aacl _aacs _aact _aacx _aada&quot;]</value>
      <webElementGuid>bc66f309-30d4-4a39-9da3-6be492993e43</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mount_0_0_YN']/div/div/div/div/div/div/div/div/section/main/div/header/section/div/h2</value>
      <webElementGuid>f4bac74d-f6ac-45a1-9784-3366eef4614d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Follow'])[1]/preceding::h2[1]</value>
      <webElementGuid>f6013e99-94ba-4226-a669-320fbc534020</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Message'])[1]/preceding::h2[1]</value>
      <webElementGuid>5aadb948-4d0e-4615-a37e-4b435486fe19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='redappledigitalhealth']/parent::*</value>
      <webElementGuid>5e8a55ec-31b5-4b4e-ac0c-6305018120b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h2</value>
      <webElementGuid>47c20f31-2072-45e9-94ff-c96622307928</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[(text() = 'redappledigitalhealth' or . = 'redappledigitalhealth')]</value>
      <webElementGuid>c636e7dc-8a4c-43a7-8f0e-d501ebde1740</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
