<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Home_nocss</name>
   <tag></tag>
   <elementGuidId>1a5acffd-f86b-4ff3-bc17-8dfe8568dd9f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//header[@id='site-header']/div/div/div/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.nocss</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>785bb411-989b-410a-a5ac-23390b1cdfcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nocss</value>
      <webElementGuid>b34aaf29-1c31-4a3c-8a25-2b8489e6a299</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://redappleapp.com/wp-content/uploads/2022/10/redapple-logo-white-v2.png</value>
      <webElementGuid>1c50cd45-1dc5-4c0d-924d-65cbcc71926f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;site-header&quot;)/div[@class=&quot;header-inner&quot;]/div[@class=&quot;site-branding show-logo&quot;]/div[@class=&quot;site-logo show&quot;]/a[@class=&quot;custom-logo-link&quot;]/img[@class=&quot;nocss&quot;]</value>
      <webElementGuid>786ef166-6d8d-4c84-ac17-1caae872a82f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='site-header']/div/div/div/a/img</value>
      <webElementGuid>cf4960d5-aa64-48db-bbad-49649984f2de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://redappleapp.com/wp-content/uploads/2022/10/redapple-logo-white-v2.png')]</value>
      <webElementGuid>97ac5366-ae11-47c6-9eb9-285553ba94e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>da9bc06d-d73c-4a12-9c41-12f7673ee2a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://redappleapp.com/wp-content/uploads/2022/10/redapple-logo-white-v2.png']</value>
      <webElementGuid>25065f7f-9662-481a-83a6-e37f5571122a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
