<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Twitter_tdb-logo-img td-retina-data td-_b1101f</name>
   <tag></tag>
   <elementGuidId>ab8e5e77-3eaa-4834-999c-cfb7a51f80a9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='tdi_32']/div/div/div/div/div/a/h1/span/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.td_block_wrap.tdb_header_logo.tdi_36.td-pb-border-top.td_block_template_1.tdb-header-align > div.tdb-block-inner.td-fix-index > a.tdb-logo-a > h1 > span.tdb-logo-img-wrap > img.tdb-logo-img.td-retina-data.td-retina-version</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>0618f430-aa8e-42a9-919d-2a0f0ea16959</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tdb-logo-img td-retina-data td-retina-version</value>
      <webElementGuid>c2ba81ac-bd84-4fbb-9a48-117f22ff311f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-retina</name>
      <type>Main</type>
      <value>//blog.redappleapp.com/wp-content/uploads/2020/08/redapple-logo.png</value>
      <webElementGuid>c84ba313-33f3-417f-87e6-3b4d87157444</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>//blog.redappleapp.com/wp-content/uploads/2020/08/redapple-logo.png</value>
      <webElementGuid>d3bfad76-38d2-41b4-9764-e0d76c4a399e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Logo</value>
      <webElementGuid>7dba9d07-8c1e-420f-9252-dd6f0c6c673d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>238</value>
      <webElementGuid>9c8667fc-f7e4-47ed-8389-ed9129252fad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>60</value>
      <webElementGuid>b59311de-db86-421c-b094-c46c568348f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tdi_32&quot;)/div[@class=&quot;vc_row tdi_33  wpb_row td-pb-row&quot;]/div[@class=&quot;vc_column tdi_35  wpb_column vc_column_container tdc-column td-pb-span12&quot;]/div[@class=&quot;wpb_wrapper&quot;]/div[@class=&quot;td_block_wrap tdb_header_logo tdi_36 td-pb-border-top td_block_template_1 tdb-header-align&quot;]/div[@class=&quot;tdb-block-inner td-fix-index&quot;]/a[@class=&quot;tdb-logo-a&quot;]/h1[1]/span[@class=&quot;tdb-logo-img-wrap&quot;]/img[@class=&quot;tdb-logo-img td-retina-data td-retina-version&quot;]</value>
      <webElementGuid>49ca3ced-97d0-4b1a-9201-c3c22aa2999b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tdi_32']/div/div/div/div/div/a/h1/span/img</value>
      <webElementGuid>be11d19b-0184-4436-aade-a1dd3e919d16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='Logo'])[2]</value>
      <webElementGuid>569b0fd6-f26d-40f8-ae93-86037501e142</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div/a/h1/span/img</value>
      <webElementGuid>f4bbd139-b3d2-4664-95b4-446d8808d05f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '//blog.redappleapp.com/wp-content/uploads/2020/08/redapple-logo.png' and @alt = 'Logo']</value>
      <webElementGuid>5f20d389-82af-42ff-9f28-94207cb8032f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
